language: node_js
node_js:
  - '4.1'

# Env
env:
  global:
    - CF_APP=ha--node-starter
    - CF_API=https://api.ng.bluemix.net/

# Deploy
# Revert to `npm install -g cf-blue-green` once  https://github.com/18F/cf-blue-green/issues/17 is resolved
before_deploy:
  - 'npm install -g git@github.com:Snugug/cf-blue-green.git#clean-deploy'
deploy:
  - provider: script
    script: cf-blue-green-travis
    on:
      branch: master
