language: node_js
node_js:
  - '4.1'

cache:
  directories:
    - node_modules

# Env
env:
  global:
    - CF_APP=ha--node-starter
    - CF_API=https://api.ng.bluemix.net/
    - CF_SPACE=Hack-Academy
    - CF_USERNAME=sam.richard@us.ibm.com

# Deploy
before_deploy:
  - npm install -g cf-blue-green
deploy:
  - provider: script
    script: cf-blue-green-travis
    on:
      branch: master
